name: comsm0018
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- h5py
- imageio
- imagesize
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- isort
- jupyter
- jupyter_client
- jupyter_console
- jupyterlab
- jupyterlab_server
- nbconvert
- nbformat
- notebook
- numpy
- pandas
- pillow
- pip
- python   # 更新为更新版本的Python
- pytorch  # 移除了具体版本号以获得最新版本
- torchvision  # 移除了具体版本号以获得最新版本
- torchaudio  # 如果需要，可以加入
- cudatoolkit   # 根据您的CUDA版本选择
- scikit-image
- scikit-learn
- scipy
- seaborn
- setuptools
- tensorboard  # 请注意，新版本的PyTorch有自己的tensorboard
- tensorflow  # 移除了具体版本号以获得最新版本
- tqdm
